openapi: 3.1.0
info:
  title: Count Your Birds
  version: '1.0'
  summary: 'API '
  contact:
    name: Nick Jakuschona
    email: info@countyourbirds.org
servers:
  - url: 'http://10.14.29.24:5000'
    description: Nick Jakuschona
paths:
  /station:
    post:
      summary: Create station
      operationId: post-station
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                required:
                  - id
                x-examples:
                  example-1:
                    id: 123
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  name: test
                  location:
                    lat: 12
                    lon: 12
                  mail:
                    adresses:
                      - mail@test.de
              properties:
                name:
                  type: string
                  minLength: 1
                location:
                  type: object
                  required:
                    - lat
                    - lon
                  properties:
                    lat:
                      type: number
                    lon:
                      type: number
                mail:
                  type: object
                  properties:
                    adresses:
                      type: array
                      description: list of email adresses which will receive a notification via e-mail about bird occurences
                      items:
                        type: string
              required:
                - name
                - location
            examples:
              Example:
                value:
                  name: Test
                  location:
                    lat: 12
                    lon: 12
                  mail:
                    adresses:
                      - e-mail@test.de
      description: Endpoint to create a new station
      parameters: []
    get:
      summary: ''
      operationId: get-station
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                x-examples:
                  example-1:
                    - station_id: 24943bb4-b902-4b32-9262-f79ecd9d69c7
                      name: Test Jan
                      location:
                        lat: 51.7676339975328
                        lng: 6.837615966796876
                description: Array of all stations
                items:
                  type: object
                  properties:
                    station_id:
                      type: string
                    name:
                      type: string
                    location:
                      type: object
                      properties:
                        lat:
                          type: number
                        lng:
                          type: number
      description: Get all stations
  '/station/{station_id}':
    parameters:
      - schema:
          type: string
        name: station_id
        in: path
        required: true
    get:
      summary: Get Measurements of one station
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    _id:
                      $oid: 61f90dee49c53fcca2a06580
                    station_id: 5dba702d-ccff-4095-8c0a-f5cbe2e1baf6
                    location:
                      lat: 51.399206
                      lon: 9.688879
                    mail:
                      adresses:
                        - mail@test.de
                    measurements:
                      environment:
                        - date: '2022-02-01 11:56:58.898282'
                          env_id: d8b8e9f5-26a5-48e8-8deb-f56615818b90
                          temp: 36
                      movements:
                        - audio: 'http://localhost:5000/uploads/audios/test.mp3'
                          detections:
                            - count:
                                Cyanistes caeruleus: 1
                              det_id: f317bdc8-39cf-4940-ac46-c48ed192c8fb
                              image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash.jpg'
                              weight: 7.6
                            - count:
                                Cyanistes caeruleus: 1
                              det_id: a874d4bf-a16a-45a6-beda-b63aa8337d63
                              image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash_1.jpg'
                              weight: 7.6
                          end_date: '123'
                          environment:
                            date: '123'
                            env_id: d80e4e89-b8f0-4ade-818d-48526dbf22eb
                            temp: 10
                          mov_id: cd20f9db-7156-4288-9687-9fb1db182982
                          start_date: '123'
                    name: Station name
                properties:
                  station_id:
                    type: string
                    minLength: 1
                    description: station id which can be used for further requests
                  name:
                    type: string
                    minLength: 1
                  location:
                    type: object
                    required:
                      - lat
                      - lon
                    properties:
                      lat:
                        type: number
                      lon:
                        type: number
                  measurements:
                    type: object
                    required:
                      - environment
                      - movements
                    properties:
                      environment:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          type: object
                          properties:
                            date:
                              type: string
                              minLength: 1
                            env_id:
                              type: string
                              minLength: 1
                            temperature:
                              type: number
                            humidity:
                              type: number
                          required:
                            - date
                            - env_id
                            - temperature
                      movements:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          type: object
                          properties:
                            mov_id:
                              type: string
                            start_date:
                              type: string
                              minLength: 1
                            end_date:
                              type: string
                              minLength: 1
                            audio:
                              type: string
                              minLength: 1
                              description: 'url to audio file '
                            video:
                              type: string
                              description: link to the video file
                            environment:
                              type: object
                              properties:
                                date:
                                  type: string
                                  minLength: 1
                                env_id:
                                  type: string
                                  minLength: 1
                                temperature:
                                  type: number
                                humidity:
                                  type: number
                              required:
                                - date
                                - env_id
                                - temperature
                            detections:
                              type: array
                              uniqueItems: true
                              minItems: 1
                              description: all detections sorted by score
                              items:
                                type: object
                                properties:
                                  latinName:
                                    type: string
                                    minLength: 1
                                  germanName:
                                    type: string
                                    minLength: 1
                                  score:
                                    type: number
                                    description: 'propability '
                                required:
                                  - latinName
                                  - germanName
                                  - score
                            weight:
                              type: number
                          required:
                            - start_date
                            - end_date
                            - audio
                  count:
                    type: array
                    description: count of birds for each day
                    items:
                      type: object
                      properties:
                        date:
                          type: object
                          properties:
                            latinName:
                              type: string
                            germanName:
                              type: string
                            amount:
                              type: number
                required:
                  - station_id
                  - name
                  - location
                  - measurements
              examples:
                example:
                  value:
                    station_id: a19bdefe-403b-4791-a220-48a857dce14f
                    name: Floriade
                    location:
                      lat: 52.357177391260805
                      lng: 5.22501826286316
                    measurements:
                      environment:
                        - env_id: 2b349c4e-18df-42a1-b15c-53f6f01928e9
                          date: '2022-07-26 15:42:41.351365'
                          temperature: 23.7
                          humidity: 45.7
                        - env_id: 8d7a1397-8e41-431d-a813-a0af5fb9642f
                          date: '2022-07-26 15:41:40.377121'
                          temperature: 23.7
                          humidity: 45.7
                      movements:
                        - mov_id: 64ed8003-c313-40e4-b234-b23c4de68fc3
                          start_date: '2022-07-26 11:29:11.676586'
                          end_date: '2022-07-26 11:29:14.717148'
                          audio: 'https://wiediversistmeingarten.org/api/uploads/audios/sound_74591.wav'
                          video: 'https://wiediversistmeingarten.org/api/uploads/videos/2022-07-26_112911.676586.mp4'
                          environment:
                            env_id: a17a2528-aa81-427f-93d7-4545149b2bec
                            date: '2022-07-26 11:16:21.366904'
                            temperature: -50
                            humidity: 1
                          weight: 1358.6345142660116
                          detections:
                            - latinName: Pyrrhula pyrrhula
                              germanName: Gimpel
                              score: 0.8823529411764706
                    count:
                      '2022-07-26':
                        - latinName: Pyrrhula pyrrhula
                          germanName: Gimpel
                          amount: 1
        '404':
          description: station not Found
      operationId: get-station-station_id
      parameters: []
      description: 'Endpoint to get one station, with all measurements'
    put:
      summary: ''
      operationId: put-station-station_id
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Station Not Found
      parameters:
        - schema:
            type: string
          in: query
          name: apikey
          description: Api key to change Data. Can be requested by provider.
      description: Change Station Data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example:
                value:
                  name: newName
        description: It can change all values of the station
    delete:
      summary: ''
      operationId: delete-station-station_id
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: Delete Station
      parameters:
        - schema:
            type: string
          in: query
          name: apikey
          description: Api key to change Data. Can be requested by provider.
  '/environment/{station_id}':
    parameters:
      - schema:
          type: string
        name: station_id
        in: path
        required: true
    post:
      summary: Send environment
      operationId: post-environment-station_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: 12
                properties:
                  id:
                    type: string
                required:
                  - id
        '404':
          description: station not found
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  date: '2022-02-01 11:56:58.898282'
                  env_id: d8b8e9f5-26a5-48e8-8deb-f56615818b90
                  temp: 36
              properties:
                date:
                  type: string
                  minLength: 1
                temperature:
                  type: number
                humidity:
                  type: number
              required:
                - date
            examples:
              example:
                value:
                  date: '2022-06-21 18:16:10.210804'
                  temperature: 10
                  humidity: 10
      description: 'Endpoint to send values of environment sensors from the station to the server '
  '/movement/{station_id}':
    parameters:
      - schema:
          type: string
        name: station_id
        in: path
        required: true
    post:
      summary: Send movement
      operationId: post-movement-station_id
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: number
                required:
                  - id
                x-examples:
                  example-1:
                    id: 123
        '404':
          description: station Not Found
      requestBody:
        content:
          multipart/form-data:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  json:
                    start_date: '123'
                    end_date: '123'
                    audio: audioKey
                    environment:
                      date: '123'
                      temp: 10
                    detections:
                      - date: '123'
                        image: imageKey1
                        weight: 7.6
                      - date: '123'
                        image: imageKey2
                        weight: 7.6
                  audioKey: files
                  imageKey1: files
                  imageKey2: files
              properties:
                json:
                  type: object
                  description: 'json object, send as file containing all objects'
                  required:
                    - start_date
                    - end_date
                    - environment
                  properties:
                    start_date:
                      type: string
                      minLength: 1
                    end_date:
                      type: string
                      minLength: 1
                    environment:
                      type: object
                      description: environment object. containing values of different sensors
                      required:
                        - date
                        - temperature
                      properties:
                        date:
                          type: string
                          minLength: 1
                        temperature:
                          type: number
                          description: 'exampe measurement, more possible'
                        humidity:
                          type: number
                audioKey:
                  description: the name "audioKey" has to be set in the json under audio. The object is the audio the file itself
                  type: object
                videoKey:
                  type: object
                  description: the name "videoKey" has to be set in the json int the detection under image. The object is the video file itself.
              required:
                - json
                - videoKey
            examples:
              example:
                value:
                  json:
                    start_date: string
                    end_date: string
                    environment:
                      date: string
                      temperature: 12
                      humidity: 12
                  audioKey: string
                  videoKey: string
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: 'The form data consist of three parts. One JSON with metadata, one videofile and one audiofile. An example request can be found here https://github.com/Birdiary/webserver/blob/main/api/example_requests.py.'
      x-code_example: null
      description: Endpoint to send data of a movement.
  /image: {}
  '/uploads/audios/{filename}':
    parameters:
      - schema:
          type: string
        name: filename
        in: path
        required: true
    get:
      summary: Get uploaded audio
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-uploads-audios-filename
      description: Get the uploaded audio
  '/uploads/videos/{filename}':
    parameters:
      - schema:
          type: string
        name: filename
        in: path
        required: true
    get:
      summary: Get image file
      tags: []
      operationId: get-uploads-images-filename
      description: Get the uploaded image
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
components:
  schemas:
    station:
      description: ''
      type: object
      x-examples:
        example-1:
          _id:
            $oid: 61f90dee49c53fcca2a06580
          station_id: 5dba702d-ccff-4095-8c0a-f5cbe2e1baf6
          location:
            lat: 51.399206
            lon: 9.688879
          mail:
            adresses:
              - tom.niers@countyourbirds.org
          measurements:
            environment:
              - date: '2022-02-01 11:56:58.898282'
                env_id: d8b8e9f5-26a5-48e8-8deb-f56615818b90
                temp: 36
            movements:
              - audio: 'http://localhost:5000/uploads/audios/test.mp3'
                detections:
                  - count:
                      Cyanistes caeruleus: 1
                    det_id: f317bdc8-39cf-4940-ac46-c48ed192c8fb
                    image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash.jpg'
                    weight: 7.6
                  - count:
                      Cyanistes caeruleus: 1
                    det_id: a874d4bf-a16a-45a6-beda-b63aa8337d63
                    image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash_1.jpg'
                    weight: 7.6
                end_date: '123'
                environment:
                  date: '123'
                  env_id: d80e4e89-b8f0-4ade-818d-48526dbf22eb
                  temp: 10
                mov_id: cd20f9db-7156-4288-9687-9fb1db182982
                start_date: '123'
          name: Peter Lustigs Station
      properties:
        station_id:
          type: string
          minLength: 1
        location:
          type: object
          required:
            - lat
            - lon
          properties:
            lat:
              type: number
            lon:
              type: number
        mail:
          type: object
          required:
            - adresses
          properties:
            adresses:
              type: array
              items:
                type: object
        measurements:
          type: object
          required:
            - environment
            - movements
          properties:
            environment:
              type: array
              uniqueItems: true
              minItems: 1
              items:
                type: object
                properties:
                  date:
                    type: string
                    minLength: 1
                  env_id:
                    type: string
                    minLength: 1
                  temp:
                    type: number
                required:
                  - date
                  - env_id
                  - temp
            movements:
              type: array
              uniqueItems: true
              minItems: 1
              items:
                type: object
                properties:
                  audio:
                    type: string
                    minLength: 1
                  detections:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        count:
                          type: object
                          properties:
                            Cyanistes caeruleus:
                              type: number
                          required:
                            - Cyanistes caeruleus
                        det_id:
                          type: string
                          minLength: 1
                        image:
                          type: string
                          minLength: 1
                        weight:
                          type: number
                      required:
                        - det_id
                        - image
                        - weight
                  end_date:
                    type: string
                    minLength: 1
                  environment:
                    type: object
                    properties:
                      date:
                        type: string
                        minLength: 1
                      env_id:
                        type: string
                        minLength: 1
                      temp:
                        type: number
                  mov_id:
                    type: string
                    minLength: 1
                  start_date:
                    type: string
                    minLength: 1
                required:
                  - audio
                  - detections
                  - end_date
                  - mov_id
                  - start_date
        name:
          type: string
          minLength: 1
      required:
        - location
        - mail
        - measurements
        - name
      examples:
        - _id:
            $oid: 61f90dee49c53fcca2a06580
          station_id: 5dba702d-ccff-4095-8c0a-f5cbe2e1baf6
          location:
            lat: 51.399206
            lon: 9.688879
          mail:
            adresses:
              - tom.niers@countyourbirds.org
          measurements:
            environment:
              - date: '2022-02-01 11:56:58.898282'
                env_id: d8b8e9f5-26a5-48e8-8deb-f56615818b90
                temp: 36
            movements:
              - audio: 'http://localhost:5000/uploads/audios/test.mp3'
                detections:
                  - count:
                      Cyanistes caeruleus: 1
                    det_id: f317bdc8-39cf-4940-ac46-c48ed192c8fb
                    image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash.jpg'
                    weight: 7.6
                  - count:
                      Cyanistes caeruleus: 1
                    det_id: a874d4bf-a16a-45a6-beda-b63aa8337d63
                    image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash_1.jpg'
                    weight: 7.6
                end_date: '123'
                environment:
                  date: '123'
                  env_id: d80e4e89-b8f0-4ade-818d-48526dbf22eb
                  temp: 10
                mov_id: cd20f9db-7156-4288-9687-9fb1db182982
                start_date: '123'
          name: Peter Lustigs Station
    movement:
      description: ''
      type: object
      x-examples:
        example-1:
          audio: 'http://localhost:5000/uploads/audios/test.mp3'
          detections:
            - count:
                Cyanistes caeruleus: 1
              det_id: f317bdc8-39cf-4940-ac46-c48ed192c8fb
              image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash.jpg'
              weight: 7.6
            - count:
                Cyanistes caeruleus: 1
              det_id: a874d4bf-a16a-45a6-beda-b63aa8337d63
              image: 'http://localhost:5000/uploads/images/svetozar-cenisev-pvqTCIOx9MQ-unsplash_1.jpg'
              weight: 7.6
          end_date: '123'
          environment:
            date: '123'
            env_id: d80e4e89-b8f0-4ade-818d-48526dbf22eb
            temp: 10
          mov_id: cd20f9db-7156-4288-9687-9fb1db182982
          start_date: '123'
      properties:
        audio:
          type: string
          minLength: 1
        detections:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              count:
                type: object
                properties:
                  Cyanistes caeruleus:
                    type: number
              det_id:
                type: string
                minLength: 1
              image:
                type: string
                minLength: 1
              weight:
                type: number
            required:
              - image
              - weight
        end_date:
          type: string
          minLength: 1
        environment:
          type: object
          properties:
            date:
              type: string
              minLength: 1
            env_id:
              type: string
              minLength: 1
            temp:
              type: number
        mov_id:
          type: string
          minLength: 1
        start_date:
          type: string
          minLength: 1
      required:
        - audio
        - detections
        - end_date
        - start_date
    environment:
      description: ''
      type: object
      x-examples:
        example-1:
          date: '2022-02-01 11:56:58.898282'
          env_id: d8b8e9f5-26a5-48e8-8deb-f56615818b90
          temp: 36
      properties:
        date:
          type: string
          minLength: 1
        env_id:
          type: string
          minLength: 1
        temp:
          type: number
  requestBodies: {}
  examples: {}
